In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline

In [3]:
df_final = pd.read_csv("../data/clean/df_final_combined.csv")
df_exp = pd.read_csv("../data/clean/experiments.csv")

In [26]:
# Merge the two tables on the 'client_id' column
df_merged = df_final.merge(df_exp[['client_id', 'variation']], on='client_id', how='left')
df_merged['variation'] = df_merged['variation'].fillna('Unknown')
# Drop rows with null value
df_merged = df_merged[df_merged['variation'] != 'Unknown']
df_merged.reset_index(drop=True, inplace=True)

In [28]:
df_merged.head(10)

,client_id,visitor_id_start,visit_id_start,process_step_start,date_time_start,visitor_id_confirm,visit_id_confirm,process_step_confirm,date_time_confirm,variation
0,169,201385055_71273495308,749567106_99161211863_557568,start,2017-04-12 20:19:36,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09,Control
1,555,402506806_56087378777,637149525_38041617439_716659,start,2017-04-15 12:57:56,402506806_56087378777,637149525_38041617439_716659,confirm,2017-04-15 13:00:34,Test
2,647,66758770_53988066587,40369564_40101682850_311847,start,2017-04-12 15:41:28,66758770_53988066587,40369564_40101682850_311847,confirm,2017-04-12 15:47:45,Test
3,722,919259913_64837298108,984487154_55831795985_521110,start,2017-04-19 14:56:16,919259913_64837298108,984487154_55831795985_521110,confirm,2017-04-19 15:00:09,Control
4,1195,766842522_69992551638,393817425_39015278493_996341,start,2017-04-05 20:15:26,766842522_69992551638,393817425_39015278493_996341,confirm,2017-04-05 20:19:31,Control
5,1197,753759429_54481946928,71862471_21202285428_848395,start,2017-04-01 17:16:24,753759429_54481946928,71862471_21202285428_848395,confirm,2017-04-01 17:17:59,Control
6,1336,920624746_32603333901,583743392_96265099036_939815,start,2017-05-08 06:05:12,920624746_32603333901,614001770_19101025926_112779,confirm,2017-05-08 08:23:00,Test
7,1516,182314299_63168583136,481123290_95510977345_707323,start,2017-04-05 15:57:22,182314299_63168583136,255400977_38039535960_779641,confirm,2017-04-06 22:30:18,Test
8,1543,498785241_50825025698,48544987_94878616044_157787,start,2017-04-05 15:10:20,498785241_50825025698,48544987_94878616044_157787,confirm,2017-04-05 15:13:54,Control
9,1643,121807985_20524560478,753205700_16851596206_134483,start,2017-06-10 07:49:27,121807985_20524560478,753205700_16851596206_134483,confirm,2017-06-10 08:00:55,Test